package com.harris.usmob.entity;

import lombok.Data;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.MongoId;

import java.util.Date;

//Ensure unique mdn
//Index by mdn, userId, (maybe) startDate for quick retrieval
//Partition? Shard?

@Data
@Document(collection = "cycle")
public class Cycle {
    @MongoId
    private String id; // primary key; auto-generated by MongoDB
    private String mdn; // phone number of a customer
    private Date startDate; // start date of billing cycle
    private Date endDate; // end date of billing cycle
    private String userId; // foreign key to the id of the user collection
    // assume userId is trustworthy (extracted from JWT) and from a higher-level microservice
}