package com.harris.usmob.entity;

import lombok.Data;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.MongoId;

import java.util.Date;

//Ensure unique mdn
//Ensure unique usageDate

//Index on mdn, userId, usageDate for quick retrieval
//Partition/shard?

@Data
@Document(collection = "daily_usage")
public class DailyUsage {
    @MongoId
    private String id; // primary key; auto-generated by MongoDB
    private String mdn; // phone number associated with the usage
    private String userId; // the customer who owns this phone number; foreign key to the id of the user collection
    private Date usageDate; // date of the usage
    private Integer usedInMb; // the usage of that day from XX-YY 00:00:00 EST to XX-YY 23:59:59 EST
}
