package com.harris.usmob.entity;

import lombok.Data;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.MongoId;

//Ensure unique email
//Index on email for efficient retrieval
//Perhaps index on name??? How often will we be searching by name?

@Data
@Document(collection = "user")
public class User {

    @MongoId
    private String id; // primary key; auto-generated by MongoDB
    private String mdn; // added by me
    private String firstName; // first name of a customer
    private String lastName; // last name of a customer
    private String email; // email of a customer
    private String password; // used for login to our system

//    public User(String firstName, String lastName, String mdn, String email, String password) {
//        this.firstName = firstName;
//        this.lastName = lastName;
//        this.mdn = mdn;
//        this.email = email;
//        this.password = password;
//    }
}